version = 1

test_patterns = [
  "**/__tests__/**",
  "**/*.spec.ts",
  "**/*.spec.js",
  "**/*.test.ts",
  "**/*.test.js"
]

exclude_patterns = [
  "node_modules",
  "bower_components",
  "out",
  "bin",
  "build",
  "dist"
]

[[analyzers]]
name = "test-coverage"
enabled = true

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = ["react"]
  environment = ["vitest"]

[[transformers]]
name = "prettier"

[[transformers]]
name = "standardjs"